"""Create core data models

Revision ID: b45ba1e4db4c
Revises: fee874e62242
Create Date: 2025-08-29 11:48:38.924441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45ba1e4db4c'
down_revision: Union[str, None] = 'fee874e62242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_trail', sa.Column('operation', sa.String(length=100), nullable=False))
    op.add_column('audit_trail', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('audit_trail', sa.Column('parameter_versions', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('outputs', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('intermediates', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('errors', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('supervisor_overrides', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('exclusions', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('corporate_actions', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('immutable_hash', sa.String(length=64), nullable=False))
    op.alter_column('audit_trail', 'input_snapshot',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('audit_trail', 'model_version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=36),
               nullable=True)
    op.alter_column('audit_trail', 'environment_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index('idx_audit_created', table_name='audit_trail')
    op.drop_index('idx_audit_entity', table_name='audit_trail')
    op.drop_index('ix_audit_trail_entity_id', table_name='audit_trail')
    op.drop_index('idx_audit_operation', table_name='audit_trail')
    op.create_index('idx_audit_operation', 'audit_trail', ['operation'], unique=False)
    op.create_index('idx_audit_initiator', 'audit_trail', ['initiator'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_trail', ['timestamp'], unique=False)
    op.drop_column('audit_trail', 'has_errors')
    op.drop_column('audit_trail', 'error_details')
    op.drop_column('audit_trail', 'record_hash')
    op.drop_column('audit_trail', 'operation_type')
    op.drop_column('audit_trail', 'parameter_snapshot')
    op.drop_column('audit_trail', 'entity_id')
    op.drop_column('audit_trail', 'parameter_version')
    op.drop_column('audit_trail', 'operation_start')
    op.drop_column('audit_trail', 'operation_end')
    op.drop_column('audit_trail', 'output_snapshot')
    op.add_column('business_indicators', sa.Column('source', sa.String(length=100), nullable=True))
    op.alter_column('business_indicators', 'ildc',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'sc',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'fc',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'bi_total',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'three_year_average',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.drop_column('business_indicators', 'source_system')
    op.add_column('capital_calculations', sa.Column('bucket', sa.Integer(), nullable=False))
    op.add_column('capital_calculations', sa.Column('supervisor_override', sa.Boolean(), nullable=False))
    op.add_column('capital_calculations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('capital_calculations', 'business_indicator',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'business_indicator_component',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'loss_component',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'operational_risk_capital',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'risk_weighted_assets',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'parameter_version',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('capital_calculations', 'model_version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=36),
               nullable=True)
    op.drop_column('capital_calculations', 'calculation_duration_ms')
    op.drop_column('capital_calculations', 'sma_bucket')
    op.drop_column('capital_calculations', 'has_supervisor_override')
    op.add_column('jobs', sa.Column('run_id', sa.String(length=36), nullable=False))
    op.add_column('jobs', sa.Column('calculation_date', sa.Date(), nullable=False))
    op.add_column('jobs', sa.Column('request_data', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('webhook_attempts', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index('idx_job_entity', table_name='jobs')
    op.drop_index('ix_jobs_job_id', table_name='jobs')
    op.create_index('idx_job_entity_date', 'jobs', ['entity_id', 'calculation_date'], unique=False)
    op.create_index(op.f('ix_jobs_run_id'), 'jobs', ['run_id'], unique=True)
    op.drop_column('jobs', 'calculation_run_id')
    op.drop_column('jobs', 'input_parameters')
    op.drop_column('jobs', 'job_id')
    op.drop_column('jobs', 'webhook_delivery_attempts')
    op.add_column('loss_events', sa.Column('event_type', sa.String(length=50), nullable=False))
    op.alter_column('loss_events', 'gross_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('loss_events', 'net_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('loss_events', 'basel_event_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('loss_events', 'business_line',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('ix_loss_events_discovery_date', table_name='loss_events')
    op.drop_column('loss_events', 'event_reference')
    op.alter_column('recoveries', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('recoveries', 'recovery_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('idx_recovery_date', 'recoveries', ['receipt_date'], unique=False)
    op.create_index('idx_recovery_loss_event', 'recoveries', ['loss_event_id'], unique=False)
    op.create_index(op.f('ix_recoveries_loss_event_id'), 'recoveries', ['loss_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recoveries_loss_event_id'), table_name='recoveries')
    op.drop_index('idx_recovery_loss_event', table_name='recoveries')
    op.drop_index('idx_recovery_date', table_name='recoveries')
    op.alter_column('recoveries', 'recovery_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('recoveries', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.add_column('loss_events', sa.Column('event_reference', sa.VARCHAR(length=100), nullable=False))
    op.create_index('ix_loss_events_discovery_date', 'loss_events', ['discovery_date'], unique=False)
    op.alter_column('loss_events', 'business_line',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('loss_events', 'basel_event_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('loss_events', 'net_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('loss_events', 'gross_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.drop_column('loss_events', 'event_type')
    op.add_column('jobs', sa.Column('webhook_delivery_attempts', sa.INTEGER(), nullable=False))
    op.add_column('jobs', sa.Column('job_id', sa.VARCHAR(length=36), nullable=False))
    op.add_column('jobs', sa.Column('input_parameters', sa.TEXT(), nullable=True))
    op.add_column('jobs', sa.Column('calculation_run_id', sa.VARCHAR(length=36), nullable=True))
    op.drop_index(op.f('ix_jobs_run_id'), table_name='jobs')
    op.drop_index('idx_job_entity_date', table_name='jobs')
    op.create_index('ix_jobs_job_id', 'jobs', ['job_id'], unique=1)
    op.create_index('idx_job_entity', 'jobs', ['entity_id'], unique=False)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_by')
    op.drop_column('jobs', 'webhook_attempts')
    op.drop_column('jobs', 'request_data')
    op.drop_column('jobs', 'calculation_date')
    op.drop_column('jobs', 'run_id')
    op.add_column('capital_calculations', sa.Column('has_supervisor_override', sa.BOOLEAN(), nullable=False))
    op.add_column('capital_calculations', sa.Column('sma_bucket', sa.INTEGER(), nullable=False))
    op.add_column('capital_calculations', sa.Column('calculation_duration_ms', sa.INTEGER(), nullable=True))
    op.alter_column('capital_calculations', 'model_version',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('capital_calculations', 'parameter_version',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('capital_calculations', 'risk_weighted_assets',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'operational_risk_capital',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'loss_component',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'business_indicator_component',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'business_indicator',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.drop_column('capital_calculations', 'updated_at')
    op.drop_column('capital_calculations', 'supervisor_override')
    op.drop_column('capital_calculations', 'bucket')
    op.add_column('business_indicators', sa.Column('source_system', sa.VARCHAR(length=50), nullable=True))
    op.alter_column('business_indicators', 'three_year_average',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('business_indicators', 'bi_total',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'fc',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'sc',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'ildc',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.drop_column('business_indicators', 'source')
    op.add_column('audit_trail', sa.Column('output_snapshot', sa.TEXT(), nullable=True))
    op.add_column('audit_trail', sa.Column('operation_end', sa.DATETIME(), nullable=True))
    op.add_column('audit_trail', sa.Column('operation_start', sa.DATETIME(), nullable=False))
    op.add_column('audit_trail', sa.Column('parameter_version', sa.VARCHAR(length=36), nullable=False))
    op.add_column('audit_trail', sa.Column('entity_id', sa.VARCHAR(length=50), nullable=False))
    op.add_column('audit_trail', sa.Column('parameter_snapshot', sa.TEXT(), nullable=False))
    op.add_column('audit_trail', sa.Column('operation_type', sa.VARCHAR(length=50), nullable=False))
    op.add_column('audit_trail', sa.Column('record_hash', sa.VARCHAR(length=64), nullable=False))
    op.add_column('audit_trail', sa.Column('error_details', sa.TEXT(), nullable=True))
    op.add_column('audit_trail', sa.Column('has_errors', sa.BOOLEAN(), nullable=False))
    op.drop_index('idx_audit_timestamp', table_name='audit_trail')
    op.drop_index('idx_audit_initiator', table_name='audit_trail')
    op.drop_index('idx_audit_operation', table_name='audit_trail')
    op.create_index('idx_audit_operation', 'audit_trail', ['operation_type'], unique=False)
    op.create_index('ix_audit_trail_entity_id', 'audit_trail', ['entity_id'], unique=False)
    op.create_index('idx_audit_entity', 'audit_trail', ['entity_id'], unique=False)
    op.create_index('idx_audit_created', 'audit_trail', ['created_at'], unique=False)
    op.alter_column('audit_trail', 'environment_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('audit_trail', 'model_version',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('audit_trail', 'input_snapshot',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('audit_trail', 'immutable_hash')
    op.drop_column('audit_trail', 'corporate_actions')
    op.drop_column('audit_trail', 'exclusions')
    op.drop_column('audit_trail', 'supervisor_overrides')
    op.drop_column('audit_trail', 'errors')
    op.drop_column('audit_trail', 'intermediates')
    op.drop_column('audit_trail', 'outputs')
    op.drop_column('audit_trail', 'parameter_versions')
    op.drop_column('audit_trail', 'timestamp')
    op.drop_column('audit_trail', 'operation')
    # ### end Alembic commands ###
