"""Initial database schema

Revision ID: fee874e62242
Revises: 65a2f8aef728
Create Date: 2025-08-29 01:45:01.777550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee874e62242'
down_revision: Union[str, None] = '65a2f8aef728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_trail', sa.Column('initiator', sa.String(length=100), nullable=False))
    op.add_column('audit_trail', sa.Column('input_snapshot', sa.Text(), nullable=False))
    op.add_column('audit_trail', sa.Column('output_snapshot', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('parameter_snapshot', sa.Text(), nullable=False))
    op.add_column('audit_trail', sa.Column('model_version', sa.String(length=20), nullable=False))
    op.add_column('audit_trail', sa.Column('parameter_version', sa.String(length=36), nullable=False))
    op.add_column('audit_trail', sa.Column('record_hash', sa.String(length=64), nullable=False))
    op.add_column('audit_trail', sa.Column('operation_start', sa.DateTime(), nullable=False))
    op.add_column('audit_trail', sa.Column('operation_end', sa.DateTime(), nullable=True))
    op.add_column('audit_trail', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('audit_trail', sa.Column('has_errors', sa.Boolean(), nullable=False))
    op.add_column('audit_trail', sa.Column('error_details', sa.Text(), nullable=True))
    op.drop_index('ix_audit_trail_timestamp', table_name='audit_trail')
    op.create_index('idx_audit_created', 'audit_trail', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_trail', ['entity_id'], unique=False)
    op.create_index('idx_audit_operation', 'audit_trail', ['operation_type'], unique=False)
    op.create_index('idx_audit_run_id', 'audit_trail', ['run_id'], unique=False)
    op.drop_column('audit_trail', 'operation')
    op.drop_column('audit_trail', 'input_data_hash')
    op.drop_column('audit_trail', 'parameter_versions')
    op.drop_column('audit_trail', 'output_data_hash')
    op.drop_column('audit_trail', 'timestamp')
    op.drop_column('audit_trail', 'data_sources')
    op.drop_column('audit_trail', 'reproducible')
    op.drop_column('audit_trail', 'additional_metadata')
    op.drop_column('audit_trail', 'user_id')
    op.drop_column('audit_trail', 'model_versions')
    op.add_column('business_indicators', sa.Column('source_system', sa.String(length=50), nullable=True))
    op.alter_column('business_indicators', 'ildc',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'sc',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'fc',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'bi_total',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'three_year_average',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('business_indicators', 'methodology',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('business_indicators', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('business_indicators', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('idx_bi_entity_date', 'business_indicators', ['entity_id', 'calculation_date'], unique=False)
    op.create_index('idx_bi_period', 'business_indicators', ['period'], unique=False)
    op.add_column('capital_calculations', sa.Column('business_indicator', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('capital_calculations', sa.Column('parameter_version', sa.String(length=36), nullable=False))
    op.add_column('capital_calculations', sa.Column('has_supervisor_override', sa.Boolean(), nullable=False))
    op.add_column('capital_calculations', sa.Column('override_reason', sa.Text(), nullable=True))
    op.add_column('capital_calculations', sa.Column('override_approver', sa.String(length=100), nullable=True))
    op.add_column('capital_calculations', sa.Column('calculation_duration_ms', sa.Integer(), nullable=True))
    op.alter_column('capital_calculations', 'methodology',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Enum('BIA', 'TSA', 'SMA', 'AMA', 'WHAT_IF', name='modelnameenum'),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'business_indicator_component',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'loss_component',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'internal_loss_multiplier',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'operational_risk_capital',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'risk_weighted_assets',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'sma_bucket',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('capital_calculations', 'ilm_gated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('capital_calculations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('idx_calc_entity_date', 'capital_calculations', ['entity_id', 'calculation_date'], unique=False)
    op.create_index('idx_calc_methodology', 'capital_calculations', ['methodology'], unique=False)
    op.create_index('idx_calc_run_id', 'capital_calculations', ['run_id'], unique=False)
    op.drop_constraint(None, 'capital_calculations', type_='foreignkey')
    op.drop_column('capital_calculations', 'created_by')
    op.drop_column('capital_calculations', 'parameter_version_id')
    op.drop_column('capital_calculations', 'business_indicator_id')
    op.add_column('jobs', sa.Column('job_id', sa.String(length=36), nullable=False))
    op.add_column('jobs', sa.Column('model_name', sa.Enum('BIA', 'TSA', 'SMA', 'AMA', 'WHAT_IF', name='modelnameenum'), nullable=False))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('jobs', sa.Column('estimated_completion_time', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('input_parameters', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('error_details', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('calculation_run_id', sa.String(length=36), nullable=True))
    op.alter_column('jobs', 'webhook_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'webhook_delivery_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_jobs_run_id', table_name='jobs')
    op.create_index('idx_job_created', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_job_entity', 'jobs', ['entity_id'], unique=False)
    op.create_index('idx_job_idempotency', 'jobs', ['idempotency_key'], unique=False)
    op.create_index('idx_job_status', 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_entity_id'), 'jobs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'created_by')
    op.drop_column('jobs', 'methodology')
    op.drop_column('jobs', 'run_id')
    op.drop_column('jobs', 'current_step')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'queued_at')
    op.drop_column('jobs', 'calculation_id')
    op.drop_column('jobs', 'estimated_completion')
    op.drop_column('jobs', 'job_type')
    op.drop_column('jobs', 'error_code')
    op.add_column('loss_events', sa.Column('event_reference', sa.String(length=100), nullable=False))
    op.add_column('loss_events', sa.Column('basel_event_type', sa.String(length=50), nullable=False))
    op.add_column('loss_events', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('loss_events', 'gross_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('loss_events', 'net_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('loss_events', 'is_outsourced',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('loss_events', 'is_pending',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('loss_events', 'is_timing_loss',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('loss_events', 'is_excluded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('loss_events', 'disclosure_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('loss_events', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('loss_events', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('idx_loss_amount', 'loss_events', ['gross_amount'], unique=False)
    op.create_index('idx_loss_discovery', 'loss_events', ['discovery_date'], unique=False)
    op.create_index('idx_loss_entity_date', 'loss_events', ['entity_id', 'accounting_date'], unique=False)
    op.create_index('idx_loss_occurrence', 'loss_events', ['occurrence_date'], unique=False)
    op.create_index(op.f('ix_loss_events_discovery_date'), 'loss_events', ['discovery_date'], unique=False)
    op.create_unique_constraint(None, 'loss_events', ['event_reference'])
    op.drop_column('loss_events', 'event_type')
    op.add_column('recoveries', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('recoveries', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('recoveries', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('recoveries', 'recovery_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recoveries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_recoveries_receipt_date'), 'recoveries', ['receipt_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recoveries_receipt_date'), table_name='recoveries')
    op.alter_column('recoveries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('recoveries', 'recovery_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recoveries', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('recoveries', 'updated_at')
    op.drop_column('recoveries', 'description')
    op.add_column('loss_events', sa.Column('event_type', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'loss_events', type_='unique')
    op.drop_index(op.f('ix_loss_events_discovery_date'), table_name='loss_events')
    op.drop_index('idx_loss_occurrence', table_name='loss_events')
    op.drop_index('idx_loss_entity_date', table_name='loss_events')
    op.drop_index('idx_loss_discovery', table_name='loss_events')
    op.drop_index('idx_loss_amount', table_name='loss_events')
    op.alter_column('loss_events', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('loss_events', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('loss_events', 'disclosure_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('loss_events', 'is_excluded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('loss_events', 'is_timing_loss',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('loss_events', 'is_pending',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('loss_events', 'is_outsourced',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('loss_events', 'net_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('loss_events', 'gross_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('loss_events', 'description')
    op.drop_column('loss_events', 'basel_event_type')
    op.drop_column('loss_events', 'event_reference')
    op.add_column('jobs', sa.Column('error_code', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('job_type', sa.VARCHAR(), nullable=False))
    op.add_column('jobs', sa.Column('estimated_completion', sa.DATETIME(), nullable=True))
    op.add_column('jobs', sa.Column('calculation_id', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('queued_at', sa.DATETIME(), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.TEXT(), nullable=True))
    op.add_column('jobs', sa.Column('current_step', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('run_id', sa.VARCHAR(), nullable=False))
    op.add_column('jobs', sa.Column('methodology', sa.VARCHAR(length=3), nullable=False))
    op.add_column('jobs', sa.Column('created_by', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'capital_calculations', ['calculation_id'], ['id'])
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_entity_id'), table_name='jobs')
    op.drop_index('idx_job_status', table_name='jobs')
    op.drop_index('idx_job_idempotency', table_name='jobs')
    op.drop_index('idx_job_entity', table_name='jobs')
    op.drop_index('idx_job_created', table_name='jobs')
    op.create_index('ix_jobs_run_id', 'jobs', ['run_id'], unique=False)
    op.alter_column('jobs', 'webhook_delivery_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'webhook_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('jobs', 'calculation_run_id')
    op.drop_column('jobs', 'error_details')
    op.drop_column('jobs', 'input_parameters')
    op.drop_column('jobs', 'estimated_completion_time')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'model_name')
    op.drop_column('jobs', 'job_id')
    op.add_column('capital_calculations', sa.Column('business_indicator_id', sa.VARCHAR(), nullable=True))
    op.add_column('capital_calculations', sa.Column('parameter_version_id', sa.VARCHAR(), nullable=False))
    op.add_column('capital_calculations', sa.Column('created_by', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'capital_calculations', 'business_indicators', ['business_indicator_id'], ['id'])
    op.drop_index('idx_calc_run_id', table_name='capital_calculations')
    op.drop_index('idx_calc_methodology', table_name='capital_calculations')
    op.drop_index('idx_calc_entity_date', table_name='capital_calculations')
    op.alter_column('capital_calculations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('capital_calculations', 'ilm_gated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('capital_calculations', 'sma_bucket',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('capital_calculations', 'risk_weighted_assets',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'operational_risk_capital',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'internal_loss_multiplier',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=15, scale=4),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'loss_component',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'business_indicator_component',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('capital_calculations', 'methodology',
               existing_type=sa.Enum('BIA', 'TSA', 'SMA', 'AMA', 'WHAT_IF', name='modelnameenum'),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.drop_column('capital_calculations', 'calculation_duration_ms')
    op.drop_column('capital_calculations', 'override_approver')
    op.drop_column('capital_calculations', 'override_reason')
    op.drop_column('capital_calculations', 'has_supervisor_override')
    op.drop_column('capital_calculations', 'parameter_version')
    op.drop_column('capital_calculations', 'business_indicator')
    op.drop_index('idx_bi_period', table_name='business_indicators')
    op.drop_index('idx_bi_entity_date', table_name='business_indicators')
    op.alter_column('business_indicators', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('business_indicators', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('business_indicators', 'methodology',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.alter_column('business_indicators', 'three_year_average',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('business_indicators', 'bi_total',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'fc',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'sc',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('business_indicators', 'ildc',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('business_indicators', 'source_system')
    op.add_column('audit_trail', sa.Column('model_versions', sa.TEXT(), nullable=True))
    op.add_column('audit_trail', sa.Column('user_id', sa.VARCHAR(), nullable=False))
    op.add_column('audit_trail', sa.Column('additional_metadata', sa.TEXT(), nullable=True))
    op.add_column('audit_trail', sa.Column('reproducible', sa.BOOLEAN(), nullable=True))
    op.add_column('audit_trail', sa.Column('data_sources', sa.TEXT(), nullable=True))
    op.add_column('audit_trail', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('audit_trail', sa.Column('output_data_hash', sa.VARCHAR(), nullable=True))
    op.add_column('audit_trail', sa.Column('parameter_versions', sa.TEXT(), nullable=True))
    op.add_column('audit_trail', sa.Column('input_data_hash', sa.VARCHAR(), nullable=False))
    op.add_column('audit_trail', sa.Column('operation', sa.VARCHAR(), nullable=False))
    op.drop_index('idx_audit_run_id', table_name='audit_trail')
    op.drop_index('idx_audit_operation', table_name='audit_trail')
    op.drop_index('idx_audit_entity', table_name='audit_trail')
    op.drop_index('idx_audit_created', table_name='audit_trail')
    op.create_index('ix_audit_trail_timestamp', 'audit_trail', ['timestamp'], unique=False)
    op.drop_column('audit_trail', 'error_details')
    op.drop_column('audit_trail', 'has_errors')
    op.drop_column('audit_trail', 'created_at')
    op.drop_column('audit_trail', 'operation_end')
    op.drop_column('audit_trail', 'operation_start')
    op.drop_column('audit_trail', 'record_hash')
    op.drop_column('audit_trail', 'parameter_version')
    op.drop_column('audit_trail', 'model_version')
    op.drop_column('audit_trail', 'parameter_snapshot')
    op.drop_column('audit_trail', 'output_snapshot')
    op.drop_column('audit_trail', 'input_snapshot')
    op.drop_column('audit_trail', 'initiator')
    # ### end Alembic commands ###
